/* generated by pull.js */
const manifest = {
  "name": "换行输入框",
  "description": "把积木上的文本输入框替换为多行输入框：按 Enter 换行，Ctrl/Cmd+Enter 确认；含换行的文本在积木上折叠为一行并显示 ↵ 与省略号。",
  "credits": [
    {
      "name": "yuan",
      "link": "https://github.com/13244431027"
    }
  ],
  "editorOnly": true,
  "noTranslations": true,
  "dynamicDisable": true,
  "tags": [
    "editor"
  ],
  "enabledByDefault": true,
  "settings": [
    {
      "name": "最大显示字符数",
      "id": "maxChars",
      "type": "integer",
      "min": 1,
      "max": 200,
      "default": 20,
      "dynamic": true
    }
  ],
  "userscripts": [
    {
      "url": "userscript.js",
      "matches": [
        "projects"
      ]
    }
  ]
};
export default manifest;
