/* generated by pull.js */
const manifest = {
  "name": "代码清理器",
  "description": "在积木右键菜单中添加\"清理独立积木\"，一键删除没有帽块的孤立脚本以及孤立的帽块。",
  "credits": [
    {
      "name": "UltimateBlockCleaner",
      "link": ""
    },
    {
      "name": "yuan",
      "link": "https://github.com/13244431027"
    }
  ],
  "editorOnly": true,
  "noTranslations": true,
  "tags": [
    "editor"
  ],
  "enabledByDefault": true,
  "userscripts": [
    {
      "url": "userscript.js",
      "matches": [
        "projects"
      ]
    }
  ]
};
export default manifest;
